### PR TITLE
Show inactive networks and allow user to select from them

### LINKED ISSUE #198: Be able to see all possible destination chains on testnet
**Repro:**
- Click on destination select

**Solve:**
Can we show all possible destinations, and grey out the ones that are the originating chain / can't be bridged to? Only showing Rinkeby is weird

photo_2022-02-03 17 42 15

photo_2022-02-03 17 42 16

### PR DESCRIPTION
**Pull request by Imti**
⚠️ Will affect dev and prod now

Closes #198

### CODE REVIEW

**Comment by Imti** [comment]
Reminder to rebase off development first

**Comment by ErinHales** [comment]
```
We want the flexibility to allow the user to select either sending or receiving chain first. Often people click on the second input, and are confused why Rinkeby is the only option.
The desired UX is:
user can click on either input to choose their network
if they have already selected one in the other input, all prohibited routes should be greyed out / not shown
Does this clarify things?
```
This makes more sense to me now.  In light of this feedback, I think we should keep other networks visible but greyed out.  If user selects a greyed out network, it would clear the other field.  What do you think?

**Comment by ErinHales** [comment]
Also, let's increase the opacity, can hardly see the greyed out ones

**Comment by Imti** [comment]
@ErinHales Fixed the PR up to support the behavior you mentioned. Best way to see it in action is via the preview link or checking it out locally 👌

**Pull request merged**
