### PR TITLE
fix: dev history

### PR DESCRIPTION
**Pull request by ErinHales**
- Filter for supported networks
 - Get txs where recipient or sender are a match
 - Change page size to 5
 - Fix updated field names (tx -> dispatchTx)

### CODE REVIEW

**Comment by odyslam** [comment]
In the preview, the "how to bridge" links to a 404 page in our docs. 

Perhaps we want to link here? https://docs.nomad.xyz/token-bridge/how-to-bridge

**Comment by yourbuddyconner** [comment]
Played around with the preview, so stoked that this is working!

**Comment by ErinHales** [comment]
> In the preview, the "how to bridge" links to a 404 page in our docs.

@odyslam This is fixed in prod and on development. This branch is just behind and will be fixed once rebased :)

**Review by Imti — APPROVED** [review]
🥳

**Pull request merged**
